### ISSUE TITLE
00:000 00:000 OC: Driver HfsPlusLegacy.efi at 1 cannot be loaded - Unsupported

### ISSUE THREAD

**Issue by feryw** [wjz304/OpenCore_Patch_Build#1]
Hi @wjz304 , I have an old laptop with BIOS only and Sandy Bridge cpu and use this mod version for about 2 months.

After updating LegacyBoot using [0.8.9_092af5d9](https://github.com/wjz304/OpenCore_Patch_Build/releases/tag/0.8.9_092af5d9) build we have error the driver cannot be loaded, and latest [HfsPlusLegacy.efi](https://github.com/acidanthera/OcBinaryData/blob/master/Drivers/HfsPlusLegacy.efi) i got error failed to entering macOS because no APFS showing to be picked.

According to [this](https://github.com/acidanthera/bugtracker/issues/2190), using diff utility on **bootX64** against official OC [here](https://github.com/dortania/build-repo/releases/download/OpenCorePkg-092af5d/OpenCore-0.8.9-RELEASE.zip) build we got
```
diff -u OpenCore-Mod-0.8.9-RELEASE/Utilities/LegacyBoot/bootX64 OpenCore-0.8.9-RELEASE/Utilities/LegacyBoot/bootX64
Binary files OpenCore-Mod-0.8.9-RELEASE/Utilities/LegacyBoot/bootX64 and OpenCore-0.8.9-RELEASE/Utilities/LegacyBoot/bootX64 differ
```

Likely in mod version, X bit in WX sections still unstripped when loaded by PE loader

**Comment by wjz304** [comment]
很抱歉，该项目仅是一个实验性的项目，它可能并不稳定. 

建议使用: ([btwise](https://gitee.com/btwise/OpenCore_NO_ACPI) 长期维护.)
https://github.com/wjz304/OpenCore_NO_ACPI_Build

**Comment by wjz304** [comment]
In addition, 0.8.9 has not been officially released,
So there are many unknowns,

**Comment by wjz304** [comment]
https://github.com/wjz304/OpenCore_Patch_Build/releases/tag/0.8.9_6c95dd3e#:~:text=Corrects%20BootInstall%20script%20syntax%20in%20LegacyBoot
我看到了官方的一些 修正，你可以测试一下。

**Comment by feryw** [comment]
> https://github.com/wjz304/OpenCore_Patch_Build/releases/tag/0.8.9_6c95dd3e#:~:text=Corrects%20BootInstall%20script%20syntax%20in%20LegacyBoot
> 我看到了官方的一些 修正，你可以测试一下。

这只是安装 LegacyBoot 的 linux 脚本支持，同时我使用强大的 macOS 脚本版本
