### ISSUE TITLE
Now not update

### ISSUE THREAD

**Issue by Sher1ocks** [wjz304/OpenCore_Patch_Build#2]
First of all Your mod help my old sandbridge laptop for hackintosh. Thank you.

Now autobot is not working after last week.
Please check issue.  Thanks in advance

**Comment by wjz304** [comment]
Sorry, I have been busy with other things recently,
Fixed, please test it.

**Comment by Sher1ocks** [comment]
> Sorry, I have been busy with other things recently, Fixed, please test it.

Thank you so much😊
